%PCA处理脸数据%
%读取脸%
facestore=readface('C:\Users\Paragon\Desktop\各种作业\facerec\d2\orl_faces');
%读取脸的数量，即取facecontainer第一列有多少行，即410行%
nfaces=size(facestore,1);
%取平均值%
meanvalue=mean(facestore);
%将脸数据转换为double格式%
facestore=double(facestore);
%设置保留维度%
k=200;
%fpca%
[lowData,eigV]=fpca(facestore,k,meanvalue);
%还原%
reconMat=lowData*eigV'+repmat(meanvalue,[nfaces,1]);
%从pca后的数据中取一个图片来还原%
img=[];
img=reconMat(1,:);
%从1行数据转换为112*92的图片%
img=reshape(img,[112,92]);
figure,imshow(uint8(img));